### ISSUE TITLE
Error when tried to install the package to Citrix R

### ISSUE THREAD

**Issue by gewliz** [sempwn/bennu#9]
Citrix R version 3.5.2
The error I got when I tried to install bennu:

**Error: HTTP error 404.
  No commit found for the ref master

  Rate limit remaining: 56/60
  Rate limit reset at: 2023-01-20 19:03:17 UTC**

```r
# insert reprex here
devtools::install_github("sempwn/bennu")
```

**Comment by sempwn** [comment]
Are you able to try installing by running the following instructions?

Before installation, you will need a C++ compiler installed to compile the Stan model. Follow the relevant instructions on configuring a C++ toolchain for your operating system [on the rstan wiki](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started).

The following must return TRUE before continuing:

```r
# install.packages("pkgbuild")
pkgbuild::has_build_tools(debug = TRUE)
```

Then, install the bennu package with:

```r
# install.packages("remotes")
remotes::install_github("sempwn/bennu")
```
